controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
  - name: fake_gripper_controller
    joints:
      - gripper_joint
      - gripper_l_finger_joint
      - gripper_r_outer_joint
      - gripper_r_finger_joint