# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: up
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint1
    - arm_joint2
    - arm_joint3
    - arm_joint4
    - arm_joint5
    - gripper_joint
    - gripper_l_finger_joint
    - gripper_r_outer_joint
    - gripper_r_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
      - arm_joint5
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_joint
      - gripper_l_finger_joint
      - gripper_r_outer_joint
      - gripper_r_finger_joint
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint1
    - arm_joint2
    - arm_joint3
    - arm_joint4
    - arm_joint5
  gains:
    arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint
    - gripper_l_finger_joint
    - gripper_r_outer_joint
    - gripper_r_finger_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_l_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_r_outer_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_r_finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1